apiVersion: "ryax.tech/v2.0"
kind: Processor
spec:
  id: collator
  human_name: Analysis results collator
  description: "Analyze a window into SCADA"
  type: python3
  version: "0.1"
  logo: search-icon.jpg
  resources:
    cpu: 2
    memory: 4G
  # dependencies:
  # - pandaPackages.pandas
  inputs:
  - help: Directory of Analysis Results
    human_name: .json results (directory)
    name: results
    type: directory
  outputs:
  - help: JSON collated analysis results
    human_name: Collated Results (json longstring)
    name: report
    type: longstring