apiVersion: "ryax.tech/v2.0"
kind: Processor
spec:
  id: analyzer
  human_name: SCADA window analyzer
  description: "Analyze a window into SCADA"
  type: python3
  version: "0.3.1"
  logo: search-icon.jpg
  resources:
    cpu: 2
    memory: 4G
  # dependencies:
  # - pandaPackages.pandas
  inputs:
  - help: Directory of Windowed Data
    human_name: Windowed Data (directory)
    name: windows
    type: directory
  outputs:
  - help: Directory of Analysis Results
    human_name: .json results (directory)
    name: results
    type: directory