apiVersion: "ryax.tech/v2.0"
kind: Processor
spec:
  id: windowmaker
  human_name: SCADA data partitioner
  description: "Split SCADA into windows"
  type: python3
  version: "0.1"
  logo: search-icon.jpg
  resources:
    cpu: 2
    memory: 4G
  # dependencies:
  # - pandaPackages.pandas
  inputs:
  - help: A parquet file to analyze
    human_name: Input Data (.parquet)
    name: data
    type: file
  outputs:
  - help: Directory of Windowed Data
    human_name: Windowed Data (directory)
    name: windows
    type: directory